countries_data: 
  url: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
  queries: 
    countries_list: '.plainlist ul'

economic_data: 
  url: https://oec.world/en/profile/country
  
  queries: 

    basic_data: '.cp-stat.cp-hero-stat'
    basic_data_name_index: 1
    basic_data_info_index: 4

    economic_activity: '.cp-section-paragraph.cp-multi-column-section-paragraph'
    overview_p: 0
    trade_p: 1
    destination_p: 2
    location_p: 3
    export_re: 'Trade: The top exports of .+? are '
    import_re: '\. The top imports of .+? are '
    exp_dest_re: 'Destinations: .+? exports mostly to '
    imp_from_re: ', and imports mostly from '