countries_data: 
  url: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
  queries: 
    countries_list: '.plainlist ul'

economic_data: 
  url: https://oec.world/en/profile/country
  
  queries: 

    basic_data: '.cp-stat.cp-hero-stat'
    basic_data_name_index: 1
    basic_data_info_index: 4

    economic_activity: '.cp-section-paragraph.cp-multi-column-section-paragraph'
    # economic_activity: '.cp-section-content.cp-multi-column-section-caption'
    overview_p: 0
    trade_p: 1
    destination_p: 2
    location_p: 3
    export_re: 'The top exports of .+ are (.+?) \((\$..+?)\), (.+?) \((\$..+?)\), (.+?) \((\$..+?)\), (.+?) \((\$..+?)\), and (.+?) \((\$..+?)\), exporting mostly to'
    # export_re: 'Exports: The top exports of .+ ?are (.+), exporting mostly to'
    import_re: 'The top imports of .+ are (.+?)? \((\$.+?)\), (.+?)? \((\$.+?)\), (.+?)? \((\$.+?)\), (.+?)? \((\$.+?)\), and (.+?)? \((\$.+?)\), importing mostly '
    # exp_dest_re: 'Destinations: .+? exports mostly to '
    # exp_dest_re: ', exporting mostly to (.+).'
    exp_dest_re: 'exporting mostly to (.+?) \((\$.+?)\), (.+?) \((\$.+?)\), (.+?) \((\$.+?)\), (.+?) \((\$.+?)\), and (.+?) \((\$.+?)\)\.$'
    imp_from_re: 'importing mostly from (.+?) \((\$.+?)\), (.+?) \((\$.+?)\), (.+?) \((\$.+?)\), (.+?) \((\$.+?)\), and (.+?) \((\$.+?)\)\.$'


